apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyweb
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyweb
  template:
    metadata:
      labels:
        app: pyweb
    spec:
      containers:
        - name: pyweb
          image: ghcr.io/biswajit-9776/Python-Demo:latest   # <-- use a real image you can pull
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: "app.py"
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
            - name: FLASK_RUN_PORT
              value: "5000"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pyweb
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: pyweb
  ports:
    - name: http
      port: 80
      targetPort: 5000
