apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-deployer
  namespace: arc-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-deployer
  namespace: apps
rules:
  - apiGroups: ["", "apps", "batch", "networking.k8s.io"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - jobs
      - cronjobs
      - services
      - configmaps
      - secrets
      - ingresses
    verbs: ["get","list","watch","create","update","patch","delete","apply"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","create","delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create","get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-deployer
  namespace: apps
subjects:
  - kind: ServiceAccount
    name: arc-deployer
    namespace: arc-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-deployer
